<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DC5CG138867R" failures="3" tests="12" name="Command line test" time="10.768" errors="0" timestamp="2022-05-02T16:58:32 NZST">
  <testcase classname="com.nahidmahmud.javaapiautomation101.reqresin.CreateUserTest" name="CreateUserId_StatusCode" time="2.225"/>
  <testcase classname="com.nahidmahmud.javaapiautomation101.reqresin.DeleteUserTest" name="DeleteUserId_StatusCode" time="0.728"/>
  <testcase classname="com.nahidmahmud.javaapiautomation101.reqresin.UpdatePatchUserTest" name="patchMethodByJson" time="0.793"/>
  <testcase classname="com.nahidmahmud.javaapiautomation101.reqresin.UpdateUserTest" name="putMethodByJson" time="0.733"/>
  <testcase classname="com.nahidmahmud.javaapiautomation101.reqresin.UserLoginTest" name="userLogin" time="0.707"/>
  <testcase classname="com.nahidmahmud.javaapiautomation101.reqresin.UserRegisterTest" name="userRegistration" time="0.704"/>
  <testcase classname="dummy.restapiexample.com.CopyOfGetAllEmployeeDataTest" name="allEmployeeData" time="1.082"/>
  <testcase classname="dummy.restapiexample.com.CreateEmployeeIDTest" name="CreateNewEmployee_Body" time="0.825"/>
  <testcase classname="dummy.restapiexample.com.CreateEmployeeIDTest" name="CreateNewEmployer_StatusCode" time="0.707">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;200&amp;gt; but was:&amp;lt;405&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<405>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:201)
at junit.framework.Assert.assertEquals(Assert.java:207)
at dummy.restapiexample.com.CreateEmployeeIDTest.CreateNewEmployer_StatusCode(CreateEmployeeIDTest.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- CreateNewEmployer_StatusCode -->
  <testcase classname="dummy.restapiexample.com.DeleteEmployeeDataTest" name="DeleteEmployer_StatusCode" time="0.73"/>
  <testcase classname="dummy.restapiexample.com.GetAllEmployeeDataTest" name="GetAllEmployeeData_StatusCode" time="0.776">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;200&amp;gt; but was:&amp;lt;429&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<429>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:201)
at junit.framework.Assert.assertEquals(Assert.java:207)
at dummy.restapiexample.com.GetAllEmployeeDataTest.GetAllEmployeeData_StatusCode(GetAllEmployeeDataTest.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- GetAllEmployeeData_StatusCode -->
  <testcase classname="dummy.restapiexample.com.UpdateEmployeeIDTest" name="UpdateAnEmployeeData_StatusCode" time="0.717">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;200&amp;gt; but was:&amp;lt;429&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<429>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:201)
at junit.framework.Assert.assertEquals(Assert.java:207)
at dummy.restapiexample.com.UpdateEmployeeIDTest.UpdateAnEmployeeData_StatusCode(UpdateEmployeeIDTest.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UpdateAnEmployeeData_StatusCode -->
</testsuite> <!-- Command line test -->
